(()=>{
'use strict';
const M=FootModel,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={fr:'Ligue 1',en:'Premier League',es:'La Liga'},bundle=JSON.parse($('#bundle').textContent),CURRENT='2026-27';
const short=s=>s.replace(/ FC(?: 1901)?$| CF$| AFC$/g,'');
const pct=p=>(100*p).toLocaleString('fr-FR',{maximumFractionDigits:1})+' %';
const date=d=>new Date(d+'T12:00:00Z').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
let datasets=bundle.datasets.map(x=>({...x,rows:M.normalize(x.data,x.league,x.season),revision:bundle.sha,checkedAt:bundle.fetchedAt}));
let archive={version:1,forecasts:[],snapshots:{}},cacheWarning='';
try{const cache=JSON.parse(localStorage.getItem('football-lab-data')||'null');if(cache)for(const c of cache){if(!names[c.league]||!/^\d{4}-\d{2}$/.test(c.season))continue;const rows=M.normalize(c.data,c.league,c.season);const i=datasets.findIndex(d=>d.league===c.league&&d.season===c.season);if(i>=0)datasets[i]={...c,rows};}}catch{cacheWarning='Les données locales n’ont pas pu être relues. Les données intégrées sont utilisées.'}
function validateArchive(a){if(a?.version!==1||!Array.isArray(a.forecasts)||a.forecasts.length>5000||!a.snapshots||typeof a.snapshots!=='object')throw Error('Sauvegarde non reconnue');
 const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(M.day(d));
 const num=(x,min,max)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;
 const ids=new Set();for(const f of a.forecasts){if(!names[f.match?.league]||typeof f.match.id!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(f.match.date)||!Array.isArray(f.pred?.probs)||f.pred.probs.length!==3||f.pred.probs.some(x=>!Number.isFinite(x)||x<0||x>1)||Math.abs(f.pred.probs.reduce((a,b)=>a+b)-1)>1e-6||!Array.isArray(f.pred.baseline)||f.pred.baseline.length!==3||f.pred.baseline.some(x=>!Number.isFinite(x)||x<0||x>1)||!Number.isFinite(Date.parse(f.savedAt))||f.savedAt.slice(0,10)>=f.match.date||!a.snapshots[f.snapshot]||ids.has(f.match.id))throw Error('Prévision invalide');ids.add(f.match.id);
 if(typeof f.match.home!=='string'||typeof f.match.away!=='string'||f.match.home.length>120||f.match.away.length>120||f.match.id!==M.id(f.match)||!/^\d{4}-\d{2}$/.test(f.match.season)||!validDate(f.pred.cutoff)||!validDate(f.pred.last)||f.pred.last>=f.pred.cutoff||f.pred.cutoff>f.savedAt.slice(0,10)||!num(f.pred.lh,.15,5)||!num(f.pred.la,.15,5)||!num(f.pred.over,0,1)||!num(f.pred.btts,0,1)||![f.pred.n,f.pred.homeN,f.pred.awayN].every(x=>Number.isInteger(x)&&x>=0&&x<100000)||!Array.isArray(f.pred.scores)||f.pred.scores.length!==5||f.pred.scores.some(x=>!Number.isInteger(x.h)||!Number.isInteger(x.a)||!num(x.h,0,24)||!num(x.a,0,24)||!num(x.p,0,1))||!/^([a-f0-9]{64})$/.test(f.snapshot))throw Error('Détail de prévision invalide');
 const snap=a.snapshots[f.snapshot];if(!Array.isArray(snap.training)||snap.training.length>10000||snap.training.some(r=>!Array.isArray(r)||r.length!==5||!validDate(r[0])||r[0]>=f.pred.cutoff||typeof r[1]!=='string'||typeof r[2]!=='string'||![r[3],r[4]].every(x=>Number.isInteger(x)&&num(x,0,99))))throw Error('Données de calcul invalides');
 }return a;}
try{const a=JSON.parse(localStorage.getItem('football-lab-archive')||'null');if(a)archive=validateArchive(a)}catch{cacheWarning+=' Le suivi local n’a pas pu être relu.'}
let tab='matches',mode='upcoming',limit=24,selected=null,refreshing=false;
const all=()=>datasets.flatMap(d=>d.rows),current=()=>datasets.find(d=>d.league===$('#league').value&&d.season===$('#season').value);
const revision=league=>datasets.filter(d=>d.league===league).map(d=>d.season+':'+d.revision).join(';');
function say(s){$('#notice').textContent=s;}
function selection(){return {league:$('#league').value,season:$('#season').value}}
function health(){const d=current(),past=d.rows.filter(m=>m.date<M.today()),played=past.filter(m=>m.score),missing=past.length-played.length,last=played.map(m=>m.date).sort().at(-1),stale=d.season===CURRENT&&(!last||M.day(M.today())-M.day(last)>10);
 $('#health').className='health'+(stale||missing?' stale':'');$('#health').textContent=`OpenFootball · ${played.length}/${past.length} matchs datés avant aujourd’hui avec un score${last?' · dernier résultat renseigné : '+date(last):''}${missing?' · '+missing+' scores manquants':''}.`+(stale?' Données possiblement en retard : actualiser ne garantit pas de nouveaux résultats.':'');}
function prediction(m){const cutoff=m.date<M.today()?m.date:M.today();return M.predict(M.fit(all(),m.league,cutoff),m.home,m.away)}
function probs(p){return `<div class="probbar">${p.probs.map(x=>`<span style="width:${x*100}%"></span>`).join('')}</div><div class="probs"><div>Domicile<b>${pct(p.probs[0])}</b></div><div>Nul<b>${pct(p.probs[1])}</b></div><div>Extérieur<b>${pct(p.probs[2])}</b></div></div>`}
function empty(title,msg){return `<div class="empty"><h2>${esc(title)}</h2><p>${esc(msg)}</p></div>`}
function card(m){const f=archive.forecasts.find(f=>f.match.id===m.id),p=f?.pred||prediction(m),historic=m.date<M.today();return `<article class="card"><div class="card-top"><span>${date(m.date)}</span><span class="badge${!m.score&&historic?' warn':''}">${m.score?'Résultat disponible':historic?'Score manquant':'Au calendrier'}</span></div><div class="teams"><span>${esc(short(m.home))}</span>${m.score?`<strong>${m.score[0]}</strong>`:''}</div><div class="teams"><span>${esc(short(m.away))}</span>${m.score?`<strong>${m.score[1]}</strong>`:''}</div>${p?probs(p):'<p class="small">Historique insuffisant pour calculer.</p>'}<p class="small">${f?'Prévision enregistrée':historic?'Simulation rétrospective':'Estimation du modèle'}${p&&(p.homeN<10||p.awayN<10)?' · peu d’historique pour une équipe':''}</p><button class="action" data-match="${esc(m.id)}">Voir l’analyse</button></article>`}
function renderMatches(){let rows=current().rows;const q=$('#search').value.trim().toLowerCase();rows=rows.filter(m=>(m.home+' '+m.away).toLowerCase().includes(q));rows=rows.filter(m=>mode==='upcoming'?m.date>=M.today():mode==='results'?!!m.score&&m.date<M.today():!m.score&&m.date<M.today());rows.sort((a,b)=>mode==='upcoming'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));
 $('#content').innerHTML=`<div class="segments">${[['upcoming','À venir'],['results','Résultats'],['missing','Scores manquants']].map(([v,t])=>`<button data-mode="${v}" class="${v===mode?'active':''}">${t}</button>`).join('')}<span class="small" style="align-self:center;margin-left:auto">${rows.length} matchs</span></div>`+(rows.length?`<div class="grid">${rows.slice(0,limit).map(card).join('')}</div>${rows.length>limit?'<button class="loadmore" id="more">Afficher davantage</button>':''}`:empty('Aucun match dans cette sélection.',mode==='upcoming'?'Choisis la saison en cours ou consulte les résultats.':'Aucun match ne correspond à ces filtres.'));}
function renderTable(){const map=new Map();for(const m of current().rows){for(const t of [m.home,m.away])if(!map.has(t))map.set(t,{team:t,n:0,w:0,d:0,l:0,gf:0,ga:0,pts:0});if(!m.score||m.date>=M.today())continue;const h=map.get(m.home),a=map.get(m.away),[x,y]=m.score;h.n++;a.n++;h.gf+=x;h.ga+=y;a.gf+=y;a.ga+=x;if(x===y){h.d++;a.d++;h.pts++;a.pts++}else{const win=x>y?h:a,lose=x>y?a:h;win.w++;win.pts+=3;lose.l++}}
 const rows=[...map.values()].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.team.localeCompare(b.team));$('#content').innerHTML=`<div class="panel"><h2>Classement calculé</h2><p>À partir des scores renseignés uniquement. Les matchs manquants, sanctions et règles particulières de départage ne sont pas intégrés : ce tableau peut différer du classement officiel.</p><div class="tablewrap"><table><thead><tr><th>#</th><th>Équipe</th>${['J','G','N','P','Diff.','Pts'].map(t=>`<th class="num">${t}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(short(r.team))}</td>${[r.n,r.w,r.d,r.l,r.gf-r.ga,r.pts].map((n,i)=>`<td class="num">${i===5?'<b>'+n+'</b>':n}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}
function report(metrics){if(!metrics)return empty('Pas encore de résultats évaluables.','Les indicateurs apparaîtront quand des résultats seront disponibles.');const m=metrics,delta=m.brier-m.baseline;return `<div class="stats"><div class="stat"><span>Matchs évalués</span><strong>${m.n}</strong></div><div class="stat"><span>Brier · plus bas = mieux</span><strong>${m.brier.toFixed(3)}</strong></div><div class="stat"><span>Issue favorite réalisée</span><strong>${pct(m.accuracy)}</strong></div></div><div class="panel"><h2>Le modèle apporte-t-il quelque chose ?</h2><p>Référence : fréquences domicile / nul / extérieur des matchs antérieurs, pondérées comme le modèle. Brier de la référence : <b>${m.baseline.toFixed(3)}</b>.</p><p class="${delta<0?'positive':'negative'}">${delta<0?'Le modèle fait mieux':'Le modèle ne fait pas mieux'} sur cet échantillon (écart : ${delta.toFixed(3)}). Ce constat ne garantit pas les performances futures.</p><p>Perte logarithmique : ${m.logloss.toFixed(3)}. Le score de Brier affiché utilise la somme des erreurs au carré sur les trois issues, entre 0 et 2.</p></div><div class="panel"><h2>Calibration · victoire à domicile</h2><p>Probabilité annoncée (vert clair) et fréquence observée (vert foncé). Les groupes contenant peu de matchs sont instables.</p>${m.bins.map((b,i)=>`<div class="calrow"><span>${i*20}–${(i+1)*20} %</span><div class="meter"><i style="width:${b.p*100}%"></i><span>${b.n?pct(b.p):'—'}</span></div><div class="meter actual"><i style="width:${b.y*100}%"></i><span>${b.n?pct(b.y):'—'}</span></div><span>${b.n} m.</span></div>`).join('')}</div>`;}
function tracked(){const s=selection(),byId=new Map(all().map(m=>[m.id,m]));return archive.forecasts.filter(f=>f.match.league===s.league&&f.match.season===s.season).map(f=>({...f,result:byId.get(f.match.id)?.score||null}));}
function renderTracking(){const rows=tracked(),done=rows.filter(r=>r.result&&r.match.date<M.today());$('#content').innerHTML=`<div class="panel"><div class="row"><h2 style="margin:0 auto 0 0">Prévisions enregistrées</h2><button id="export">Exporter</button><label><span class="small">Importer une sauvegarde</span><input id="import" type="file" accept="application/json,.json"></label></div><p>Les prévisions sont figées sur cet appareil. HTML et Android ont chacun leur stockage ; utilise l’export/import pour les transférer. Les archives importées restent déclaratives, sans certification externe d’horodatage.</p><p>${rows.length} prévisions dans cette sélection · ${done.length} résultats évaluables.</p></div>`+report(M.metrics(done.map(r=>({pred:r.pred,score:r.result}))))+(rows.length?`<div class="panel tablewrap"><table><thead><tr><th>Match</th><th>Enregistré</th><th>1 / N / 2</th><th>Résultat</th></tr></thead><tbody>${rows.slice().reverse().map(r=>`<tr><td>${esc(short(r.match.home))}<br>${esc(short(r.match.away))}<br><span class="small">${date(r.match.date)}</span></td><td>${date(r.savedAt.slice(0,10))}</td><td>${r.pred.probs.map(pct).join('<br>')}</td><td>${r.result?r.result.join(' – '):'En attente'}</td></tr>`).join('')}</tbody></table></div>`:'');}
function renderLab(){const s=selection(),bt=M.backtest(all(),s.league,s.season);$('#content').innerHTML=`<div class="panel"><h2>Rejouer le passé, sans voir le futur</h2><p>À chaque date, le modèle utilise uniquement les scores de dates strictement antérieures. Simulation sur les résultats actuellement disponibles, avec paramètres fixes : ce n’est pas une prévision publiée à l’époque, ni une preuve de performance future.</p><p>Modèle : Poisson lissé v1 · ${bt.skipped} matchs exclus faute d’historique. Le score des matchs manquants n’est jamais remplacé par zéro.</p></div>`+report(bt.metrics);}
function render(){health();$('#savedCount').textContent=archive.forecasts.length;$('#searchWrap').hidden=tab!=='matches';const titles={matches:['Le terrain d’observation.','Des prévisions explicables. Des résultats pour les éprouver.'],table:['Les forces en présence.','Un classement reconstitué à partir des scores disponibles.'],tracking:['Confronter les prévisions.','Ce qui a été enregistré, puis ce qui s’est passé.'],lab:['Mettre le modèle à l’épreuve.','Un test chronologique, comparé à une référence simple.']};$('#heading').textContent=titles[tab][0];$('#subtitle').textContent=titles[tab][1];document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));({matches:renderMatches,table:renderTable,tracking:renderTracking,lab:renderLab}[tab])();}
function showDialog(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;if(!$('#details').open)$('#details').showModal()}
function detail(id){const m=all().find(x=>x.id===id);if(!m)return;selected=m;const stored=archive.forecasts.find(f=>f.match.id===id),p=stored?.pred||prediction(m),historical=m.date<M.today();showDialog('Analyse du match',`<div class="eyebrow">${esc(names[m.league])} · ${date(m.date)}</div><h2>${esc(short(m.home))}<br><span style="font-weight:400;color:var(--muted)">contre ${esc(short(m.away))}</span></h2>${m.score?`<p>Résultat renseigné : <b>${m.score.join(' – ')}</b></p>`:''}${p?`${probs(p)}<h3>Scores les plus probables</h3><div class="scoregrid">${p.scores.map(s=>`<div class="scorebox"><strong>${s.h} – ${s.a}</strong><span>${pct(s.p)}</span></div>`).join('')}</div><h3>Autres probabilités · 90 minutes</h3><div class="detailstats"><div>Plus de 2,5 buts<strong>${pct(p.over)}</strong></div><div>Moins de 2,5 buts<strong>${pct(1-p.over)}</strong></div><div>Les deux équipes marquent<strong>${pct(p.btts)}</strong></div><div>Au moins une équipe ne marque pas<strong>${pct(1-p.btts)}</strong></div></div><p class="small">${historical&&!stored?'Simulation rétrospective avec les données actuelles. ':''}Buts moyens du modèle : ${p.lh.toFixed(2)} / ${p.la.toFixed(2)}. Ces moyennes ne sont pas des xG issus des tirs.</p><details><summary>Comprendre ce calcul</summary><p>${p.n} matchs d’entraînement, tous datés avant le ${date(p.cutoff)}. Dernier résultat utilisé : ${date(p.last)}. Historique disponible : ${p.homeN} matchs pour le domicile, ${p.awayN} pour l’extérieur.</p><p>Les buts marqués et encaissés à domicile/extérieur sont pondérés par leur ancienneté. Demi-vie : 180 jours. Lissage : 8 matchs équivalents à la moyenne du championnat. Les moyennes de buts sont bornées entre 0,15 et 5. Pas de données sur les blessures, compositions, tirs ou absences.</p><p>Les buts des deux équipes sont supposés indépendants. La grille des scores couvre 0 à 24 buts par équipe et est normalisée. Ce modèle initial n’est pas Dixon–Coles ; ses paramètres n’ont pas été optimisés sur la saison affichée.</p></details><p class="small">Dates fournies par la source ; les heures ne sont pas affichées car leur fuseau n’est pas confirmé. Enregistrement autorisé uniquement avant le jour du match, selon la date UTC.</p>${stored?'<p class="badge">Prévision déjà enregistrée, elle ne sera pas remplacée.</p>':m.date>M.today()&&!m.score?'<button class="primary" id="saveForecast">Enregistrer cette prévision</button>':'<p class="small">Enregistrement fermé pour ce match. Les simulations restent consultables.</p>'}`:'<p>Historique insuffisant : au moins 60 matchs antérieurs sont nécessaires.</p>'}`);}
async function saveForecast(){const m=selected;if(!m||m.date<=M.today()||m.score)return;const p=prediction(m);if(!p||archive.forecasts.some(f=>f.match.id===m.id))return;const b=$('#saveForecast');b.disabled=true;
 try{const training=all().filter(x=>x.league===m.league&&x.score&&x.date<p.cutoff&&M.day(p.cutoff)-M.day(x.date)<=1096).map(x=>[x.date,x.home,x.away,...x.score]);const payload=JSON.stringify({league:m.league,cutoff:p.cutoff,training,revision:revision(m.league)});const hash=await digest(payload);const snapshot=hash;const next=JSON.parse(JSON.stringify(archive));next.snapshots[snapshot]={league:m.league,cutoff:p.cutoff,training,revision:revision(m.league)};next.forecasts.push({match:m,pred:p,savedAt:new Date().toISOString(),snapshot});localStorage.setItem('football-lab-archive',JSON.stringify(next));archive=next;detail(m.id);render();say('Prévision enregistrée sur cet appareil, avec ses données de calcul.');}catch{b.disabled=false;say('Enregistrement impossible : stockage indisponible ou plein. Aucune prévision ajoutée.');}}
async function digest(s){if(!globalThis.crypto?.subtle)throw Error('Un navigateur récent avec un contexte sécurisé est nécessaire');const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('')}
async function refresh(){if(refreshing)return;refreshing=true;$('#refresh').disabled=true;$('#refresh').textContent='Actualisation…';say('Lecture des données OpenFootball…');let count=0;const failures=[];
 for(const league of Object.keys(names)){try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);let text;try{const r=await fetch(`https://raw.githubusercontent.com/openfootball/football.json/master/${CURRENT}/${league}.1.json`,{signal:controller.signal,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);text=await r.text()}finally{clearTimeout(timer)}if(text.length>1500000)throw Error('Fichier trop volumineux');const data=JSON.parse(text),rows=M.normalize(data,league,CURRENT),rev=await digest(text);const i=datasets.findIndex(d=>d.league===league&&d.season===CURRENT);const previous=datasets[i];const lost=previous.rows.filter(m=>m.score).some(m=>!rows.some(r=>r.id===m.id&&r.score));if(lost)throw Error('La source retirerait des scores déjà connus ; mise à jour ignorée');datasets[i]={league,season:CURRENT,data,rows,revision:rev,checkedAt:new Date().toISOString()};count++;}catch(e){failures.push(names[league]+': '+e.message)}}
 try{localStorage.setItem('football-lab-data',JSON.stringify(datasets.filter(d=>d.season===CURRENT).map(({rows,...d})=>d)))}catch{failures.push('La mise à jour ne peut pas être conservée sur cet appareil')}
 refreshing=false;$('#refresh').disabled=false;$('#refresh').textContent='Actualiser';render();say(`${count}/3 championnats relus. ${failures.length?failures.join(' · '):'La date du dernier résultat permet de juger la fraîcheur réelle de la source.'}`);}
function download(){const text=JSON.stringify({...archive,exportedAt:new Date().toISOString()},null,2),name='football-lab-suivi-'+M.today()+'.json';if(window.FootballNative){FootballNative.exportJson(text);return}const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importFile(file){if(!file)return;try{if(file.size>15000000)throw Error('Fichier trop volumineux');const incoming=validateArchive(JSON.parse(await file.text())),next=JSON.parse(JSON.stringify(archive));let n=0;for(const f of incoming.forecasts){if(next.forecasts.some(x=>x.match.id===f.match.id))continue;next.forecasts.push(f);next.snapshots[f.snapshot]=incoming.snapshots[f.snapshot];n++}localStorage.setItem('football-lab-archive',JSON.stringify(next));archive=next;render();say(`${n} prévisions importées. Les prévisions existantes sont conservées.`)}catch(e){say('Import impossible : '+e.message)}}
function method(){showDialog('Sources & méthode',`<div class="eyebrow">UNE EXPÉRIENCE REPRODUCTIBLE</div><h2>Du résultat à la probabilité.</h2><p>Football Lab 1.0.0 utilise un modèle original Poisson lissé. Tout le calcul s’effectue sur ton appareil, sans tokens ni abonnement.</p><h3>Données</h3><p><a href="https://github.com/openfootball/football.json" target="_blank" rel="noopener">OpenFootball / football.json</a> : calendriers et résultats déclarés dans le domaine public. Instantané intégré récupéré le ${date(bundle.fetchedAt.slice(0,10))}, révision ${esc(bundle.sha.slice(0,12))}. Saisons 2023–2024 à 2026–2027. Le bouton Actualiser relit uniquement la saison 2026–2027 ; les archives restent figées pour cette version.</p><p>Les sources communautaires peuvent être incomplètes, corrigées ou en retard. Un score absent reste inconnu. Les noms d’équipes sont ceux de la source : un changement de nom peut réduire l’historique reconnu. Les mises à jour ne remplacent jamais les probabilités déjà enregistrées.</p><h3>Modèle</h3><p>Forces offensives et défensives calculées séparément à domicile et à l’extérieur ; historique limité aux 3 dernières années, pondération exponentielle de demi-vie 180 jours, lissage de 8 matchs équivalents. Les forces relatives sont multipliées par la moyenne des buts du championnat, puis transformées en probabilités par deux lois de Poisson indépendantes.</p><p>Aucun ajustement Dixon–Coles, aucune blessure ou composition intégrée. Ce modèle de départ est volontairement simple et peut faire moins bien que la référence. Il ne calcule aucune mise ni aucun ticket.</p><h3>Évaluation</h3><p>Le laboratoire recalcule chaque match avec les seules dates antérieures, en excluant tous les matchs du même jour. Les résultats historiques disponibles aujourd’hui peuvent avoir été corrigés depuis : ces simulations ne remplacent pas le suivi prospectif.</p><p>Le score de Brier et la perte logarithmique mesurent la qualité des probabilités. Le tableau de calibration porte sur la victoire à domicile. Les matchs sans résultat sont exclus et restent signalés.</p><h3>Ton suivi</h3><p>Chaque prévision est enregistrée avant le jour du match, avec les paramètres, les probabilités et les scores d’entraînement. L’horloge est celle de l’appareil : ce n’est pas une certification indépendante. Les reports de date peuvent empêcher le rapprochement automatique ; aucun résultat n’est deviné.</p><p>Le stockage est local. L’export JSON conserve les données nécessaires pour reproduire le calcul. Un effacement des données du navigateur ou une désinstallation peut supprimer le suivi.</p>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render()}if(b.dataset.mode){mode=b.dataset.mode;limit=24;render()}if(b.dataset.match)detail(b.dataset.match);if(b.id==='more'){limit+=24;render()}if(b.id==='saveForecast')saveForecast();if(b.id==='export')download()});
$('#refresh').onclick=refresh;$('#method').onclick=method;$('#closeDialog').onclick=()=>$('#details').close();$('#details').addEventListener('click',e=>{if(e.target===$('#details'))$('#details').close()});$('#league').onchange=()=>{limit=24;render()};$('#season').onchange=()=>{limit=24;if($('#season').value!==CURRENT)mode='results';else mode='upcoming';render()};$('#search').oninput=()=>{limit=24;renderMatches()};document.addEventListener('change',e=>{if(e.target.id==='import')importFile(e.target.files[0])});$('.brand').onclick=e=>{e.preventDefault();tab='matches';render()};render();if(cacheWarning)say(cacheWarning);
})();
