/* Personal grid, market display, optional bookmaker quotes and visible-app polling. */
(function(root){
'use strict';
function create(h){
 const {M,D,K,C,O,esc,pct,names,when,date}=h,$=s=>document.querySelector(s);
 const B=root.FootOddsAnalysis,number=n=>n.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2});
 const points=n=>n===null?'—':((Math.round(n*1000)===0?'':n>0?'+':'−')+Math.abs(n*100).toLocaleString('fr-FR',{minimumFractionDigits:1,maximumFractionDigits:1})+' pts');
 let choices={format:C.FORMAT,version:1,picks:[]},events=[],oddsKey='',oddsBusy=false,oddsQuota=null,oddsMessage='',oddsAt=null,auto=true,autoPaused=false;
 let choiceView='upcoming',choiceLeague='all',choiceDays=14,choiceState='all',historyDays='all',choiceLimit=40,confidenceLeague='all',confidenceGroup='all',confidenceDays=14,confidenceLimit=24;
 const oddsAttempts=new Map(),leagueFetched=new Map(),eventFetched=new Map();let activeMatch=null,lastAuto=Date.now(),pollCursor=0;
 try{const value=JSON.parse(localStorage.getItem(C.STORE)||'null');if(value)choices=C.validate(value)}catch{h.say('La sauvegarde de tes choix est illisible. Aucune donnée n’a été remplacée.')}
 try{const value=JSON.parse(localStorage.getItem(O.STORE)||'null');if(value)events=O.validateCache(value).events}catch{}
 try{auto=localStorage.getItem('football-lab-auto-results')!=='off'}catch{}
 function preserve(fn){const top=window.scrollY,body=$('#dialogBody'),dialogTop=body?.scrollTop||0,details=$('#details'),detailsTop=details?.scrollTop||0;fn();window.scrollTo(0,top);if(body)body.scrollTop=dialogTop;if(details)details.scrollTop=detailsTop}
 function save(next){localStorage.setItem(C.STORE,JSON.stringify(next));choices=next}
 function quote(m,id){return O.average(O.find(m,events,h.all()),id)}
 function formatOdd(q){return q?q.mean.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
 function oddLabel(q){return q?'Cote moyenne '+formatOdd(q)+' · '+q.books.length+' source'+(q.books.length>1?'s':'')+(q.stale?' · relevé ancien':''):'Cote non fournie'}
 function oddsDetail(q){
  const stats=B.quoteStats(q);if(!stats)return '';
  return '<details class="quote-sources"><summary>Comparer '+stats.n+' source(s) · relevé '+esc(new Date(q.fetchedAt).toLocaleString('fr-FR'))+'</summary><p class="small">The Odds API · région Europe. Cotes observées pour ce marché précis ; tous les bookmakers ne sont pas couverts.</p><dl class="quote-range"><div><dt>Minimum</dt><dd>'+number(stats.min)+'</dd></div><div><dt>Moyenne</dt><dd>'+number(stats.mean)+'</dd></div><div><dt>Maximum</dt><dd>'+number(stats.max)+'</dd></div><div><dt>Écart max. − min.</dt><dd>'+number(stats.spread)+'</dd></div></dl><label class="quote-sort">Trier les sources<select data-quote-sort><option value="price">Cote décroissante</option><option value="name">Nom du bookmaker</option><option value="time">Relevé le plus récent</option></select></label><div class="tablewrap"><table class="bookmaker-table"><caption>Cotes et probabilités implicites brutes</caption><thead><tr><th>Bookmaker</th><th class="num">Cote</th><th class="num">1 / cote</th><th>Relevé</th></tr></thead><tbody>'+B.sortBooks(stats.books).map(b=>'<tr data-price="'+b.price+'" data-at="'+esc(b.at)+'" data-book-name="'+esc(b.title)+'" data-book-key="'+esc(b.key)+'"><td>'+esc(b.title)+'</td><td class="num">'+number(b.price)+'</td><td class="num">'+pct(b.rawProbability)+'</td><td><time datetime="'+esc(b.at)+'">'+esc(new Date(b.at).toLocaleString('fr-FR'))+'</time>'+(b.stale?'<small class="quote-old">Relevé ancien</small>':'')+'</td></tr>').join('')+'</tbody></table></div><p class="small">1 / cote inclut la marge : ce n’est pas une probabilité corrigée ni une mesure de certitude.</p></details>';
 }
 function oddsAnalysis(m,p){return B.analyze(O.find(m,events,h.all()),p)}
 function quoteFreshness(m){const event=O.find(m,events,h.all()),now=Date.now();return event?event.id+'|'+event.quotes.map(q=>B.freshness(q,event.fetchedAt,event.kickoff,now)).join(','):'none'}
 function oddsDossier(m,p){return D.eligible(m)?B.dossier(oddsAnalysis(m,p)):null}
 function comparisonPanel(m,p){
  const analysis=oddsAnalysis(m,p),groups=analysis.groups.filter(g=>g.id==='h2h'||g.books.length||g.excluded.length),reasons={'incomplete':'issues manquantes ou en double','invalid':'relevé invalide','started':'match commencé','stale':'relevé ancien','different-times':'horodatages différents'};
  return '<section class="odds-analysis" id="matchOddsAnalysis"><h3>Modèle et marché</h3><p class="small">Les probabilités du marché sont normalisées séparément pour chaque bookmaker, puis moyennées. Les calculs ne changent pas notre modèle. Un écart ne démontre ni une meilleure prévision ni une rentabilité.</p>'+groups.map(g=>'<details class="odds-comparison-group" data-comparison-group="'+esc(g.id)+'" '+(g.id==='h2h'?'open':'')+'><summary>'+esc(g.label)+' · '+g.books.length+' source(s) utilisable(s)</summary>'+(g.consensus?g.outcomes.map((id,i)=>'<div class="probability-comparison" data-market-outcome="'+esc(id)+'"><strong>'+esc(K.labels[id])+'</strong><dl><div><dt>Modèle</dt><dd>'+ (g.model[i]===null?'—':pct(g.model[i]))+'</dd></div><div><dt>Marché normalisé</dt><dd>'+pct(g.consensus[i])+'</dd></div><div><dt>Écart modèle − marché</dt><dd>'+points(g.differences[i])+'</dd></div></dl></div>').join(''):'<p class="small">Comparaison indisponible : aucun ensemble complet de cotes récentes et au même instant pour un bookmaker. Charge les cotes de ce match ou consulte les sources exclues.</p>')+'<details class="normalization-details"><summary>Vérifier le calcul et les sources</summary><p>Pour chaque bookmaker : probabilité brute = 1 / cote ; surcote = somme des probabilités brutes − 1 ; probabilité normalisée = probabilité brute / leur somme. La surcote n’est pas le bénéfice réalisé du bookmaker. Chaque bookmaker retenu compte autant dans la moyenne.</p>'+(g.books.length?'<div class="tablewrap"><table><caption>Probabilités normalisées par bookmaker</caption><thead><tr><th>Bookmaker</th><th class="num">Surcote</th>'+g.outcomes.map(id=>'<th class="num">'+esc(id)+'</th>').join('')+'<th>Relevé</th></tr></thead><tbody>'+g.books.map(b=>'<tr><td>'+esc(b.title)+'</td><td class="num">'+points(b.margin).replace(' pts',' %')+'</td>'+b.probabilities.map(v=>'<td class="num">'+pct(v)+'</td>').join('')+'<td>'+esc(new Date(b.at).toLocaleString('fr-FR'))+'</td></tr>').join('')+'</tbody></table></div>':'')+(g.excluded.length?'<p class="small">Sources exclues de cette normalisation :</p><ul>'+g.excluded.map(b=>'<li>'+esc(b.title)+' · '+esc(reasons[b.reason])+'</li>').join('')+'</ul>':'')+'</details></details>').join('')+'<p class="small">Les doubles chances se recouvrent : leurs trois cotes ne sont pas normalisées ensemble. Aucun historique de variations, de cote d’ouverture ou de clôture n’est ajouté à cette étape.</p></section>';
 }
 function findPick(m,market='1x2'){return choices.picks.find(p=>p.id===D.key(m)+'|'+market)}
 function selectedForMarket(m,id){return ['1','N','2'].includes(id)?findPick(m,'1x2')?.choices.includes(id):!!findPick(m,id)}
 function statuses(){return choices.picks.map(p=>{const s=C.status(p,h.all());return {...p,...s,match:s.match||p.match,recordMatch:p.match}})}
 function sourceQuality(league){return Object.keys(names).filter(l=>league==='all'||league===l).map(l=>{const d=h.dataset(l,h.currentSeason),health=d?D.health(d.rows):null;return '<span>'+esc(names[l])+' · '+(health?health.done+'/'+health.expected+' résultats attendus'+(health.last?' · dernier : '+date(health.last):''):'données absentes')+'</span>'}).join('')}
 function leagueOptions(value){return [['all','Tous les championnats'],...Object.entries(names)].map(([v,t])=>'<option value="'+v+'" '+(v===value?'selected':'')+'>'+esc(t)+'</option>').join('')}
 function daysOptions(value){return [7,14,30].map(n=>'<option value="'+n+'" '+(n===value?'selected':'')+'>'+n+' prochains jours</option>').join('')}
 function eligibleRows(league,days){const end=M.day(M.today())+days;return h.all().filter(m=>m.season===h.currentSeason&&(league==='all'||m.league===league)&&!m.score&&!m.conflict&&['UNKNOWN','SCHEDULED','TIMED'].includes(m.status)&&(m.kickoff?Date.parse(m.kickoff)>Date.now():m.date>=M.today())&&M.day(m.date)<=end).sort((a,b)=>(a.kickoff||a.date).localeCompare(b.kickoff||b.date)||a.home.localeCompare(b.home))}
 function pickStats(){const rows=statuses().filter(r=>choiceLeague==='all'||r.match.league===choiceLeague),done=rows.filter(r=>['hit','miss'].includes(r.state)),groups=[['Simples',r=>r.market==='1x2'&&r.choices.length===1],['Doubles',r=>r.market==='1x2'&&r.choices.length===2],['Triples',r=>r.market==='1x2'&&r.choices.length===3],['Autres marchés',r=>r.market!=='1x2']];return '<div class="stats"><div class="stat"><span>Choix conservés</span><strong>'+rows.length+'</strong></div><div class="stat"><span>Réussis / manqués</span><strong>'+done.filter(r=>r.state==='hit').length+' / '+done.filter(r=>r.state==='miss').length+'</strong></div><div class="stat"><span>En attente</span><strong>'+rows.filter(r=>r.state==='waiting').length+'</strong></div></div><div class="choice-breakdown">'+groups.map(([name,f])=>{const rs=done.filter(f),hits=rs.filter(r=>r.state==='hit').length;return '<span>'+name+' : '+(rs.length?hits+'/'+rs.length:'aucun résultat évalué')+'</span>'}).join('')+'</div>'}
 function autoLabel(){return !auto?'Actualisation automatique désactivée.':autoPaused?'Actualisation automatique suspendue après une erreur de clé ou de quota. Active une clé valide ou appuie sur Actualiser pour réessayer.':'Résultats relus toutes les 5 minutes tant que l’application est visible et que des choix attendent un résultat. Aucune analyse IA automatique.'}
 function renderChoices(){
  const records=statuses().filter(r=>(choiceLeague==='all'||r.match.league===choiceLeague)&&(choiceState==='all'||r.state===choiceState)&&(historyDays==='all'||Date.parse(r.savedAt)>=Date.now()-Number(historyDays)*86400000)),rows=eligibleRows(choiceLeague,choiceDays);
  $('#content').innerHTML='<div class="panel choice-intro"><div class="row"><div><h2>Ma grille continue</h2><p>Coche 1, N ou 2. Tu peux choisir un simple, un double ou un triple. Tes choix sont conservés dès que tu coches, puis verrouillés au début du match.</p></div><button id="exportChoices" '+(!choices.picks.length?'disabled':'')+'>Exporter mes choix</button></div><div class="row"><label class="auto-switch"><input id="autoResults" type="checkbox" '+(auto?'checked':'')+'> Actualiser les résultats automatiquement</label><button id="refreshChoiceResults">Actualiser maintenant</button></div><p class="small" id="autoResultsStatus">'+esc(autoLabel())+' Hors connexion, les derniers résultats conservés restent consultables. Les clés sont à ressaisir à chaque ouverture.</p><details><summary>Transférer mon historique</summary><p class="small">Chaque version conserve son historique sur cet appareil. L’import ajoute les choix absents et garde tes choix existants.</p><input id="importChoices" type="file" accept="application/json,.json"></details></div>'+pickStats()+'<div class="workspace-filters"><label>Championnat<select id="choiceLeague">'+leagueOptions(choiceLeague)+'</select></label><label '+(choiceView!=='upcoming'?'hidden':'')+'>Période<select id="choiceDays">'+daysOptions(choiceDays)+'</select></label><label '+(choiceView==='upcoming'?'hidden':'')+'>État<select id="choiceState">'+[['all','Tous les états'],['waiting','En attente'],['hit','Réussis'],['miss','Manqués'],['excluded','À vérifier'],['void','Annulés / administratifs']].map(([v,t])=>'<option value="'+v+'" '+(choiceState===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><label '+(choiceView==='upcoming'?'hidden':'')+'>Choix enregistrés<select id="historyDays">'+[['all','Tout l’historique'],['7','7 derniers jours'],['30','30 derniers jours'],['90','90 derniers jours']].map(([v,t])=>'<option value="'+v+'" '+(historyDays===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label></div><div class="segments">'+[['upcoming','Tous les matchs à venir'],['selected','Mes lignes 1/N/2'],['history','Tout mon historique']].map(([v,t])=>'<button data-choice-view="'+v+'" class="'+(choiceView===v?'active':'')+'" aria-pressed="'+(choiceView===v)+'">'+t+'</button>').join('')+'</div><div class="source-quality small">'+sourceQuality(choiceLeague)+'</div><p class="small">La grille porte sur le résultat à 90 minutes. Une rencontre sans horaire confirmé ferme avant le jour du match (UTC). Les reports restent en attente ; les annulations et conflits sont séparés du bilan.</p>';
  let html='';
  if(choiceView==='upcoming')html=rows.length?'<div class="choice-grid">'+rows.slice(0,choiceLimit).map(m=>gridRow(m)).join('')+'</div>'+more(rows.length):h.empty('Aucun match à venir dans cette période.','Élargis la période ou actualise le calendrier.');
  else if(choiceView==='selected'){const r=records.filter(r=>r.market==='1x2').sort((a,b)=>b.savedAt.localeCompare(a.savedAt));html=r.length?'<div class="choice-grid">'+r.slice(0,choiceLimit).map(r=>gridRow(r.match,r)).join('')+'</div>'+more(r.length):h.empty(choices.picks.length?'Aucune ligne dans ces filtres.':'Ta grille attend tes premiers choix.',choices.picks.length?'Modifie le filtre d’état ou de période.':'Ouvre Tous les matchs à venir et coche une ou plusieurs cases.');}
  else {const r=records.sort((a,b)=>b.savedAt.localeCompare(a.savedAt));html=r.length?r.slice(0,choiceLimit).map(historyRow).join('')+more(r.length):h.empty(choices.picks.length?'Aucun choix dans ces filtres.':'Aucun choix enregistré.',choices.picks.length?'Modifie le filtre d’état ou de période.':'Tes cases 1/N/2 et les marchés ajoutés depuis les analyses apparaîtront ici.');}
  $('#content').insertAdjacentHTML('beforeend',html);
 }
 function more(count){return count>choiceLimit?'<button id="moreChoices" class="loadmore">Afficher davantage · '+Math.min(choiceLimit,count)+' / '+count+'</button>':''}
 function gridRow(m,record=null){
  const resolved=D.resolve(m,h.all())||m,pick=findPick(m),status=record||pick&&C.status(pick,h.all()),p=h.prediction(resolved),locked=!D.eligible(resolved)||!p,qs=pick?.quotes||{};
  return '<article class="choice-row" data-choice-row="'+esc(D.key(m))+'"><div class="choice-match"><span class="small">'+esc(names[m.league]+' · '+when(resolved))+'</span><button class="choice-title" data-match="'+esc(resolved.id||m.id||M.id(m))+'">'+esc(m.home)+'<br><span>'+esc(m.away)+'</span></button>'+(status?'<span class="choice-status '+status.state+'">'+esc(status.label)+(status.score?' · '+status.score.join(' – ')+' · '+status.outcome:'')+'</span>':'<span class="small">'+(locked?'Choix fermé · horaire ou historique à vérifier':'Choisis ton résultat')+'</span>')+'</div><div class="choice-boxes">'+['1','N','2'].map((c,i)=>{const q=choiceView==='upcoming'?quote(resolved,c):qs[c],prob=pick&&choiceView!=='upcoming'?pick.probabilities[c]:p?.probs[i];return '<label class="choice-cell '+(pick?.choices.includes(c)?'chosen':'')+' '+(status?.outcome===c?'actual-result':'')+'"><input type="checkbox" data-pick-match="'+esc(D.key(m))+'" data-pick-outcome="'+c+'" '+(pick?.choices.includes(c)?'checked':'')+' '+(locked?'disabled':'')+' aria-label="'+esc(m.home+' contre '+m.away+' : '+c)+'"><strong>'+c+'</strong><span>'+ (prob!==undefined&&prob!==null?pct(prob):'')+'</span><small>'+esc(q?(choiceView==='upcoming'?'Cote ':'Cote gardée ')+formatOdd(q)+(q.stale?' · ancienne':''):'Cote —')+'</small></label>'}).join('')+'</div>'+(pick?'<div class="choice-note small">'+pick.choices.length+' case(s) · probabilité conservée : '+pct(pick.probability)+' · choix du '+esc(new Date(pick.savedAt).toLocaleString('fr-FR'))+'</div>':'<div class="choice-note small">'+esc(p&& (p.homeN<10||p.awayN<10)?'Historique limité pour une équipe.':p?'Probabilités estimées par le modèle.':'Calcul indisponible.')+'</div>')+'</article>';
 }
 function historyRow(r){const market=r.market==='1x2'?r.choices.join(' / '):K.labels[r.market],q=r.market==='1x2'&&r.choices.length!==1?null:r.quotes[r.choices[0]];return '<article class="choice-history"><div><span class="small">'+esc(names[r.match.league]+' · '+when(r.match))+'</span><h3>'+esc(r.match.home)+' / '+esc(r.match.away)+'</h3><p>'+esc(market)+' · probabilité conservée : <b>'+pct(r.probability)+'</b></p><p class="small">Choix du '+esc(new Date(r.savedAt).toLocaleString('fr-FR'))+' · '+esc(oddLabel(q))+'</p>'+oddsDetail(q)+'</div><span class="choice-status '+r.state+'">'+esc(r.label)+(r.score?' · '+r.score.join(' – '):'')+'</span><button data-choice-inspect="'+esc(r.id)+'">Voir mon choix</button></article>'}
 function inspectChoice(id){const p=choices.picks.find(p=>p.id===id);if(!p)return;const s=C.status(p,h.all());h.showDialog('Choix enregistré','<h2>'+esc(p.match.home)+'<br>'+esc(p.match.away)+'</h2><p>'+esc(when(s.match||p.match))+'</p><p class="choice-status '+s.state+'">'+esc(s.label)+(s.score?' · '+s.score.join(' – '):'')+'</p><h3>'+esc(p.market==='1x2'?p.choices.join(' / '):K.labels[p.market])+'</h3><p>Probabilité conservée : <b>'+pct(p.probability)+'</b> · '+esc(p.model||'modèle non précisé')+'</p><p class="small">Choix du '+esc(new Date(p.savedAt).toLocaleString('fr-FR'))+'. Le résultat est rapproché des sources actuelles à chaque actualisation.</p>'+p.choices.map(c=>'<h3>'+esc(K.labels[c])+'</h3><p>'+esc(oddLabel(p.quotes[c]))+'</p>'+oddsDetail(p.quotes[c])).join(''));}
 function renderConfidence(){
  const candidates=[];let limited=0;
  for(const m of eligibleRows(confidenceLeague,confidenceDays)){const p=h.prediction(m);if(!p||p.homeN<10||p.awayN<10){limited++;continue}for(const market of K.from(p))if(market.p>=.8&&(confidenceGroup==='all'||market.group===confidenceGroup))candidates.push({m,p,market})}
  candidates.sort((a,b)=>b.market.p-a.market.p||(a.m.kickoff||a.m.date).localeCompare(b.m.kickoff||b.m.date));
  const groups=['all','Résultat · 1/N/2','Double chance','Total de buts','Les deux équipes marquent'];
  $('#content').innerHTML='<div class="panel"><h2>Probabilité estimée ≥ 80 %</h2><p>Les marchés à forte probabilité selon le modèle, parmi les trois championnats suivis. Une estimation de 80 % peut échouer ; elle n’est pas une certitude ni une mesure de rentabilité.</p><div class="workspace-filters"><label>Championnat<select id="confidenceLeague">'+leagueOptions(confidenceLeague)+'</select></label><label>Horizon<select id="confidenceDays">'+daysOptions(confidenceDays)+'</select></label><label>Marché<select id="confidenceGroup">'+groups.map(g=>'<option value="'+esc(g)+'" '+(confidenceGroup===g?'selected':'')+'>'+esc(g==='all'?'Tous les marchés':g)+'</option>').join('')+'</select></label></div><div class="source-quality small">'+sourceQuality(confidenceLeague)+'</div><p class="small">'+candidates.length+' marchés retenus · '+limited+' rencontres exclues faute d’historique suffisant (10 matchs par équipe minimum). Les résultats peuvent être incomplets ou anciens. Les probabilités affichées ici ne sont pas recalibrées à partir des cotes.</p><button id="loadOddsAll">'+(oddsBusy?'Lecture des cotes…':'Charger les cotes · jusqu’à 6 crédits')+'</button><p class="small" id="oddsPageStatus">'+esc(oddsStatus())+'</p></div>'+(candidates.length?'<div class="confidence-grid">'+candidates.slice(0,confidenceLimit).map(({m,p,market})=>{const q=quote(m,market.id),picked=selectedForMarket(m,market.id);return '<article class="confidence-card"><span class="small">'+esc(names[m.league]+' · '+when(m))+'</span><button class="choice-title" data-match="'+esc(m.id)+'">'+esc(m.home)+'<br>'+esc(m.away)+'</button><p>'+esc(market.label)+'</p><div class="confidence-values"><div><span>Probabilité estimée</span><strong>'+pct(market.p)+'</strong></div><div><span>Cote moyenne</span><strong>'+formatOdd(q)+'</strong></div></div><p class="small">'+esc(q?q.books.length+' source(s) · '+(q.stale?'relevé ancien':new Date(q.fetchedAt).toLocaleTimeString('fr-FR')):'Non fournie pour ce marché')+'</p><button data-add-market="'+esc(market.id)+'" data-market-match="'+esc(D.key(m))+'" '+(picked||!D.eligible(m)?'disabled':'')+'>'+ (picked?'Choix enregistré':'Ajouter à mes choix')+'</button>'+oddsDetail(q)+'<p class="small">'+esc(h.modelLabel(p))+' · dernier résultat utilisé : '+date(p.last)+'</p></article>'}).join('')+'</div>'+(candidates.length>confidenceLimit?'<button id="moreConfidence" class="loadmore">Afficher davantage</button>':''):h.empty('Aucun marché ne remplit ce seuil.','Élargis l’horizon ou consulte les probabilités dans Matchs. Aucun choix n’est ajouté automatiquement.'));
  $('#loadOddsAll').disabled=oddsBusy;
 }
 function marketPanel(m,p){
  const markets=K.from(p),event=O.find(m,events,h.all()),prematch=D.eligible(m),history=!!m.score||m.date<M.today();
  return '<section id="matchMarkets"><div class="section-title"><h3>Marchés · 90 minutes</h3><button data-odds-match="'+esc(D.key(m))+'" '+(oddsBusy||history?'disabled':'')+'>Cotes détaillées · jusqu’à 7 crédits</button></div><p class="small" id="matchOddsStatus">'+esc(history?'Cotes actuelles indisponibles après match. Les cotes observées au moment de tes choix sont conservées dans Ma grille.':event?'Cotes : The Odds API · '+new Date(event.fetchedAt).toLocaleString('fr-FR')+'. '+(Date.now()-Date.parse(event.fetchedAt)>O.TTL?'Relevé ancien.':''):'Cotes non chargées. Active ta clé de cotes dans Connexions et clés.')+'</p>'+comparisonPanel(m,p)+'<p class="small">Moyenne des bookmakers disponibles pour chaque marché. Une cote manquante reste « — ». Les cases et boutons enregistrent des choix personnels pour observation.</p>'+['Résultat · 1/N/2','Double chance','Total de buts','Les deux équipes marquent'].map(group=>'<details class="market-group" '+(group==='Résultat · 1/N/2'?'open':'')+'><summary>'+esc(group)+'</summary><div class="market-header"><span>Issue</span><span>Probabilité</span><span>Cote moy.</span><span>Mon choix</span></div>'+markets.filter(x=>x.group===group).map(x=>{const q=history?null:quote(m,x.id),pick=selectedForMarket(m,x.id);return '<div class="market-row"><span>'+esc(x.label)+'</span><strong>'+pct(x.p)+'</strong><span class="market-odd">'+formatOdd(q)+(q?'<small>'+q.books.length+' source(s)'+(q.stale?' · ancien':'')+'</small>':'<small>Non fournie</small>')+'</span><button data-add-market="'+esc(x.id)+'" data-market-match="'+esc(D.key(m))+'" '+(pick||!prematch?'disabled':'')+' aria-label="'+esc('Ajouter '+x.label+' à mes choix')+'">'+(pick?'Ajouté':'Ajouter')+'</button></div>'+oddsDetail(q)}).join('')+'</details>').join('')+'<p class="small">Cotes de championnat : 1/N/2 et total principal, jusqu’à 2 crédits. Marchés détaillés d’un match : jusqu’à 5 crédits, plus jusqu’à 2 crédits si son identifiant doit d’abord être recherché. Les requêtes restent manuelles, avec cache de 15 minutes. La couverture des doubles chances, des totaux alternatifs et des deux équipes qui marquent varie selon les bookmakers.</p></section>';
 }
 function mountMatch(m,p){activeMatch={key:D.key(m),pred:p,freshness:quoteFreshness(m)};const old=$('#matchMarkets');if(old)old.outerHTML=marketPanel(m,p);else $('#dialogBody').insertAdjacentHTML('beforeend',marketPanel(m,p))}
 function refreshMatchMarkets(updateAI=false){if(!activeMatch||!$('#details').open||!$('#matchMarkets'))return;const m=h.all().find(m=>D.key(m)===activeMatch.key);if(m){const opened=[...document.querySelectorAll('.market-group[open]')].map(d=>d.querySelector('summary').textContent),comparisons=[...document.querySelectorAll('.odds-comparison-group[open]')].map(d=>d.dataset.comparisonGroup);preserve(()=>{mountMatch(m,activeMatch.pred);document.querySelectorAll('.market-group').forEach(d=>d.open=opened.includes(d.querySelector('summary').textContent));document.querySelectorAll('.odds-comparison-group').forEach(d=>d.open=comparisons.includes(d.dataset.comparisonGroup));if(updateAI)h.oddsUpdated?.(m,activeMatch.pred)})}}
 function oddsStatus(){return (oddsMessage?oddsMessage+' ':oddsKey?'Clé saisie pour cette session. ':'Clé de cotes facultative, à configurer dans Connexions et clés. ')+(oddsQuota?'Quota communiqué : '+(oddsQuota.remaining??'—')+' crédits restants · dernier appel : '+(oddsQuota.last??'—')+' crédit(s). ':'')+(oddsAt?'Dernière consultation : '+new Date(oddsAt).toLocaleString('fr-FR')+'.':'')}
 function oddsCard(){return '<section class="connection-card odds-connection"><h2>Cotes des bookmakers</h2><p class="small">Connexion facultative à The Odds API. Les probabilités et le suivi fonctionnent sans cette clé.</p><label for="oddsKey">Clé The Odds API</label><input type="password" id="oddsKey" autocomplete="off" spellcheck="false" placeholder="Ta clé de cotes"><div class="row"><button id="useOddsKey" class="primary">Activer la clé</button><button id="forgetOddsKey">Oublier</button><button id="loadOddsLeague">Charger les cotes du championnat</button></div><p id="oddsKeyStatus" class="small" role="status">'+esc(oddsStatus())+'</p><p class="small">Formule gratuite annoncée : 500 crédits par mois. 1 région Europe ; jusqu’à 2 crédits par championnat, jusqu’à 5 pour les marchés détaillés d’un match. Aucun chargement automatique de cotes. Pas de cotes historiques payantes.</p><a class="web-link" href="https://the-odds-api.com/#get-access" target="_blank" rel="noopener">Obtenir une clé The Odds API</a></section>'}
 function paintOddsConnection(){if($('#oddsKeyStatus'))$('#oddsKeyStatus').textContent=oddsStatus();for(const id of ['useOddsKey','forgetOddsKey','loadOddsLeague','loadOddsAll'])if($('#'+id))$('#'+id).disabled=oddsBusy;if($('#oddsPageStatus'))$('#oddsPageStatus').textContent=oddsStatus();}
 async function oddsTransport(league,eventId,key){
  if(window.FootballNative?.fetchOdds)return new Promise((resolve,reject)=>{const id=++nativeSeq,t=setTimeout(()=>{nativePending.delete(id);reject(Error('Délai de connexion dépassé'))},22000);nativePending.set(id,r=>{clearTimeout(t);r.ok?resolve({data:r.data,quota:r.quota}):reject(Error('The Odds API · HTTP '+(r.status||'indisponible')))});try{FootballNative.fetchOdds(id,O.SPORTS[league],eventId||'',key)}catch{clearTimeout(t);nativePending.delete(id);reject(Error('Connexion Android indisponible'))}});
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);let url,options;
  if(h.hasRelay){url='/api/odds';options={method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({league,...(eventId?{eventId}:{}),key})}}
  else {url=new URL('https://api.the-odds-api.com/v4/sports/'+O.SPORTS[league]+(eventId?'/events/'+eventId+'/odds':'/odds'));url.search=new URLSearchParams({apiKey:key,regions:'eu',markets:eventId?'h2h,totals,alternate_totals,btts,double_chance':'h2h,totals',oddsFormat:'decimal',dateFormat:'iso'}).toString();options={credentials:'omit',headers:{Accept:'application/json'}}}
  try{const r=await fetch(url,{...options,redirect:'error',cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('The Odds API · HTTP '+r.status+(r.status===401?' : clé refusée':r.status===429?' : quota atteint':''));const reader=r.body?.getReader(),parts=[];let size=0;if(!reader)throw Error('Réponse indisponible');try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>2500000){await reader.cancel();throw Error('Réponse trop volumineuse')}parts.push(value)}}finally{reader.releaseLock()}const all=new Uint8Array(size);let at=0;for(const p of parts){all.set(p,at);at+=p.length}const data=JSON.parse(new TextDecoder().decode(all));if(h.hasRelay)return data;const quota={};for(const [field,name]of [['remaining','x-requests-remaining'],['used','x-requests-used'],['last','x-requests-last']]){const s=r.headers.get(name);quota[field]=s!==null&&/^\d+$/.test(s)?Number(s):null}return {data,quota};}catch(e){if(e.name==='TypeError')throw Error('Connexion de cotes impossible : réseau ou CORS. Utilise la version navigateur connectée.');if(e.name==='AbortError')throw Error('Délai de connexion dépassé');throw e}finally{clearTimeout(timer)}
 }
 const nativePending=new Map();let nativeSeq=0;window.footballOddsResult=(id,result)=>{const cb=nativePending.get(id);if(cb){nativePending.delete(id);cb(result)}};
 async function loadOdds(league,eventId=null){
  if(!oddsKey)throw Error('Active ta clé The Odds API dans Connexions et clés.');
  const key=league+'|'+(eventId||'league'),last=eventId?eventFetched.get(key):leagueFetched.get(league);
  if(last&&Date.now()-last<O.TTL){oddsMessage='Dernier relevé réutilisé (cache de 15 minutes).';return}
  if(Date.now()-(oddsAttempts.get(key)||0)<60000)throw Error('Attends une minute avant de réessayer ce relevé.');
  if(oddsQuota?.remaining===0)throw Error('Quota de cotes épuisé. Attends son renouvellement ou active une autre clé.');
  oddsAttempts.set(key,Date.now());const r=await oddsTransport(league,eventId,oddsKey),now=new Date().toISOString();
  if(r.quota)oddsQuota=Object.fromEntries(['remaining','used','last'].map(k=>[k,Number.isInteger(r.quota[k])&&r.quota[k]>=0?r.quota[k]:null]));
  const incoming=O.sanitize(r.data,league,now);if(eventId&&(incoming.length!==1||incoming[0].id!==eventId))throw Error('Événement de cotes incorrect');
  events=O.merge(events,incoming,{league:eventId?null:league,eventId});
  try{localStorage.setItem(O.STORE,JSON.stringify({version:1,events}))}catch{h.say('Cotes affichées pour cette session ; stockage indisponible.')}
  if(eventId)eventFetched.set(key,Date.now());else leagueFetched.set(league,Date.now());oddsAt=now;
  const matched=incoming.filter(e=>O.match(e,h.all())).length;oddsMessage=names[league]+' : '+incoming.length+' rencontres reçues, '+matched+' rapprochées.'+(matched<incoming.length?' Les équipes ou horaires non rapprochés sont ignorés.':'');
 }
 async function oddsAction(leagues,eventMatch=null){
  if(oddsBusy)return;
  if(!oddsKey){h.say('Pour afficher les cotes réelles, active ta clé The Odds API dans Connexions et clés.');if(!$('#details').open)h.openConnections();return}
  oddsBusy=true;paintOddsConnection();let errors=[];
  try{for(const league of leagues){try{if(eventMatch){let event=O.find(eventMatch,events,h.all());if(!event){await loadOdds(league);event=O.find(eventMatch,events,h.all())}if(!event)throw Error('Ce match n’a pas de correspondance vérifiée chez le fournisseur de cotes.');await loadOdds(league,event.id)}else await loadOdds(league)}catch(e){errors.push(String(e.message||'Connexion impossible').split(oddsKey).join('[clé masquée]').slice(0,240))}}}
  finally{oddsBusy=false;if(errors.length)oddsMessage=errors.join(' · ');paintOddsConnection();if(['choices','confidence'].includes(h.tab()))preserve(()=>h.render());refreshMatchMarkets(true);h.say(oddsStatus())}
 }
 function addMarket(market,key){const m=h.all().find(m=>D.key(m)===key);if(!m)return;try{const result=['1','N','2'].includes(market),group=result?'1x2':market,selected=result?['1','N','2'].filter(c=>c===market||findPick(m,'1x2')?.choices.includes(c)):[market],quotes={};for(const c of selected){const q=quote(m,c);if(q)quotes[c]=q}save(C.put(choices,m,group,selected,activeMatch?.key===key&&$('#details').open&&$('#matchMarkets')?activeMatch.pred:h.prediction(m),quotes));refreshMatchMarkets();if(['choices','confidence'].includes(h.tab()))preserve(()=>h.render());h.say(result?'Case cochée dans Ma grille.':'Choix enregistré. Tu le retrouveras dans Ma grille → Tout mon historique.')}catch(e){h.say('Choix non enregistré : '+e.message)}}

 async function importChoices(file){if(!file)return;try{if(file.size>10000000)throw Error('Fichier trop volumineux');const incoming=JSON.parse(await file.text()),result=C.merge(choices,incoming);save(result.value);preserve(()=>h.render());h.say(result.added+' choix importés · '+result.kept+' choix existants conservés.')}catch(e){h.say('Import impossible : '+e.message)}finally{if($('#importChoices'))$('#importChoices').value=''}}
 function click(b){
  if(b.dataset.choiceView){choiceView=b.dataset.choiceView;choiceLimit=40;renderChoices();return true}
  if(b.dataset.choiceInspect){inspectChoice(b.dataset.choiceInspect);return true}
  if(b.dataset.addMarket){addMarket(b.dataset.addMarket,b.dataset.marketMatch);return true}
  if(b.dataset.oddsMatch){const m=h.all().find(m=>D.key(m)===b.dataset.oddsMatch);if(m)oddsAction([m.league],m);return true}
  if(b.id==='exportChoices'){h.exportJSON(choices,'football-lab-mes-choix-'+M.today()+'.json');return true}
  if(b.id==='refreshChoiceResults'){autoPaused=false;h.refresh();return true}
  if(b.id==='moreChoices'){choiceLimit+=40;renderChoices();return true}
  if(b.id==='moreConfidence'){confidenceLimit+=24;renderConfidence();return true}
  if(b.id==='useOddsKey'){if(oddsBusy)return true;const key=$('#oddsKey').value.trim();if(!/^[A-Za-z0-9_-]{10,128}$/.test(key)){oddsMessage='Format de clé incorrect.'}else{oddsKey=key;oddsQuota=null;oddsMessage='Clé saisie, non vérifiée. Appuie sur Charger les cotes pour la vérifier.';oddsAttempts.clear();leagueFetched.clear();eventFetched.clear();$('#oddsKey').value=''}paintOddsConnection();return true}
  if(b.id==='forgetOddsKey'){if(!oddsBusy){oddsKey='';oddsQuota=null;oddsMessage='Clé oubliée.';$('#oddsKey').value='';paintOddsConnection()}return true}
  if(b.id==='loadOddsLeague'){oddsAction([h.currentLeague()]);return true}
  if(b.id==='loadOddsAll'){oddsAction(Object.keys(names).filter(l=>confidenceLeague==='all'||confidenceLeague===l));return true}
  return false;
 }
 function change(e){
  const el=e.target;
  if(el.hasAttribute('data-quote-sort')){const body=el.closest('.quote-sources')?.querySelector('tbody');if(body){const rows=[...body.children],books=rows.map(r=>({key:r.dataset.bookKey,title:r.dataset.bookName,price:Number(r.dataset.price),at:r.dataset.at})),ordered=B.sortBooks(books,el.value);for(const b of ordered)body.appendChild(rows.find(r=>r.dataset.bookKey===b.key))}return true}
  if(el.dataset.pickMatch){const m=h.all().find(m=>D.key(m)===el.dataset.pickMatch);if(!m)return true;const previous=findPick(m),set=new Set(previous?.choices||[]);el.checked?set.add(el.dataset.pickOutcome):set.delete(el.dataset.pickOutcome);const selected=['1','N','2'].filter(c=>set.has(c)),quotes={};for(const c of selected){const q=quote(m,c);if(q)quotes[c]=q}try{save(C.put(choices,m,'1x2',selected,h.prediction(m),quotes));preserve(()=>renderChoices());const input=[...document.querySelectorAll('[data-pick-match]')].find(x=>x.dataset.pickMatch===el.dataset.pickMatch&&x.dataset.pickOutcome===el.dataset.pickOutcome);input?.focus({preventScroll:true});h.say(selected.length?'Choix conservé sur cet appareil.':'Ligne retirée de ta grille.')}catch(err){el.checked=!el.checked;h.say('Choix non enregistré : '+err.message)}return true}
  if(el.id==='importChoices'){importChoices(el.files[0]);return true}
  if(el.id==='autoResults'){auto=el.checked;autoPaused=false;try{localStorage.setItem('football-lab-auto-results',auto?'on':'off')}catch{}if($('#autoResultsStatus'))$('#autoResultsStatus').textContent=autoLabel();return true}
  const fields={choiceLeague:v=>choiceLeague=v,choiceDays:v=>choiceDays=Number(v),choiceState:v=>choiceState=v,historyDays:v=>historyDays=v,confidenceLeague:v=>confidenceLeague=v,confidenceDays:v=>confidenceDays=Number(v),confidenceGroup:v=>confidenceGroup=v};if(fields[el.id]){fields[el.id](el.value);choiceLimit=40;confidenceLimit=24;h.render();return true}return false;
 }
 function autoInfo(){return {enabled:auto,paused:autoPaused,pending:statuses().filter(r=>r.state==='waiting'||r.state==='excluded').length}}
 function resetAuto(){autoPaused=false}
 function refreshed({automatic=false,errors=[]}={}){lastAuto=Date.now();if(automatic&&errors.some(e=>/HTTP (?:401|403|429)/.test(e)))autoPaused=true;if($('#autoResultsStatus'))$('#autoResultsStatus').textContent=autoLabel();refreshMatchMarkets(true)}
 async function tick(){
  if(document.visibilityState==='visible'&&activeMatch&&$('#details').open&&$('#matchMarkets')){const m=h.all().find(m=>D.key(m)===activeMatch.key);if(m&&quoteFreshness(m)!==activeMatch.freshness)refreshMatchMarkets(true)}
  if(document.visibilityState!=='visible'||!auto||autoPaused||h.refreshing()||Date.now()-lastAuto<5*60000)return;
  const pending=statuses().filter(r=>r.state==='waiting'||r.state==='excluded');if(!pending.length)return;
  // At most two seasons per cycle: no more than six football-data calls per minute.
  const seasons=[...new Set(pending.map(r=>r.match.season))].sort().reverse(),selected=[];for(let n=0;n<Math.min(2,seasons.length);n++)selected.push(seasons[(pollCursor+n)%seasons.length]);pollCursor=(pollCursor+selected.length)%seasons.length;
  lastAuto=Date.now();await h.refresh({automatic:true,seasons:selected});
 }
 setInterval(tick,30000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')tick()});window.addEventListener('focus',tick);
 function shortcuts(){const rows=statuses(),done=rows.filter(r=>['hit','miss'].includes(r.state));return '<section class="workspace-shortcuts"><button data-tab="choices"><strong>Ma grille 1/N/2</strong><span>'+choices.picks.length+' choix · '+rows.filter(r=>r.state==='waiting').length+' en attente'+(done.length?' · '+done.filter(r=>r.state==='hit').length+'/'+done.length+' réussis':'')+'</span></button><button data-tab="confidence"><strong>Probabilité estimée ≥ 80 %</strong><span>Tous les championnats · marchés et cotes disponibles</span></button></section>'}
 return {renderChoices,renderConfidence,marketPanel,mountMatch,oddsCard,paintOddsConnection,click,change,shortcuts,autoInfo,resetAuto,refreshed,tick,quote,oddsStatus,preserve,oddsDossier,count:()=>choices.picks.length};
}
root.FootWorkspace={create};
})(typeof window!=='undefined'?window:globalThis);
