const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('assert/strict'),path=require('path');
(async()=>{const html=fs.readFileSync(path.join(__dirname,'../../football-lab.html'));const server=http.createServer((q,r)=>r.end(html));await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:850},timezoneId:'Europe/Paris'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-10-09T12:00:00Z'));await page.route('https://**/*',r=>r.abort());await page.goto(`http://127.0.0.1:${server.address().port}`);await page.locator('nav [data-tab="matches"]').click();const fixture=JSON.parse(fs.readFileSync('/tmp/football-v11-fixture.json'));const name=fixture.matches[0].homeTeam.name;
// Save a v1-compatible record before changing dates/provider.
await page.locator('#search').fill(name);await page.locator('[data-match]').first().click();await page.locator('#saveForecast').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('football-lab-archive')||'{}').forecasts?.length===1);const original=await page.evaluate(()=>localStorage.getItem('football-lab-archive'));await page.locator('#closeDialog').click();
async function load(data){await page.locator('#menuToggle').click();await page.locator('#sources').click();await page.locator('#viewData').click();await page.locator('#importData').setInputFiles({name:'matches.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>!document.querySelector('#details').open)}
await load(fixture);await page.locator('[data-match]').first().click();assert((await page.locator('#dialogBody').textContent()).includes('20:00'));assert((await page.locator('#dialogBody').textContent()).includes('déjà enregistrée'));await page.locator('#closeDialog').click();
const changed=JSON.parse(JSON.stringify(fixture));changed.matches[0].utcDate='2026-11-01T18:00:00Z';changed.matches[0].status='POSTPONED';await load(changed);await page.locator('[data-mode="postponed"]').click();assert((await page.locator('#content').textContent()).includes('Reporté'));assert.equal(await page.evaluate(()=>localStorage.getItem('football-lab-archive')),original);await page.reload();await page.locator('nav [data-tab="tracking"]').click();assert((await page.locator('#content').textContent()).includes('Report :'));assert.equal(await page.evaluate(()=>localStorage.getItem('football-lab-archive')),original);
// Import a final 0–0 for this moved match, then evaluate the original frozen probabilities.
changed.matches[0].status='FINISHED';changed.matches[0].score.fullTime={home:0,away:0};await page.clock.setFixedTime(new Date('2026-11-02T12:00:00Z'));await load(changed);assert((await page.locator('#content').textContent()).includes('0 – 0'));assert.equal(await page.locator('.stat').first().innerText(),'Matchs évalués\n1');
// Wrong competition is rejected atomically, preserving source data and forecast archive.
await page.locator('#menuToggle').click();await page.locator('#sources').click();await page.locator('#viewData').click();const before=await page.evaluate(()=>localStorage.getItem('football-lab-data-v11'));const wrong={...fixture,competition:{code:'PL'}};await page.locator('#importData').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(wrong))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Import de données impossible'));assert.equal(await page.evaluate(()=>localStorage.getItem('football-lab-data-v11')),before);await page.locator('#closeDialog').click();
// Key never enters any local storage/export.
await page.locator('#menuToggle').click();await page.locator('#sources').click();await page.locator('#fdKey').fill('TESTKEY_ONLY_12345');await page.locator('#useKey').click();await page.locator('#closeDialog').click();assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('TESTKEY_ONLY_12345'));
await page.locator('#menuToggle').click();await page.locator('#sources').click();await page.locator('#viewData').click();const downloadPromise=page.waitForEvent('download');await page.locator('#exportData').click();const dl=await downloadPromise;assert(!fs.readFileSync(await dl.path(),'utf8').includes('TESTKEY_ONLY_12345'));await page.locator('#closeDialog').click();assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/football-v11-tracking.png',fullPage:false});console.log('Calendar UI: import, timezone, reports, old forecast preservation, final result matching, atomic failures and key privacy PASS');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
