const assert=require('node:assert/strict');
const M=require('../src/model.js'),K=require('../src/markets.js'),C=require('../src/choices.js'),D=require('../src/data.js');
const now=Date.parse('2026-10-10T12:00:00Z'),m={league:'fr',season:'2026-27',date:'2026-10-11',home:'A FC',away:'B FC',kickoff:'2026-10-11T18:00:00Z',status:'TIMED',provider:'football-data',providerId:100};m.id=M.id(m);
const p={...M.grid(1.5,1),lh:1.5,la:1,version:M.VERSION};let v={format:C.FORMAT,version:1,picks:[]};
v=C.put(v,m,'1x2',['1','N'],p,{},now);assert.equal(v.picks.length,1);assert.ok(Math.abs(v.picks[0].probability-(p.probs[0]+p.probs[1]))<1e-12);
const before=JSON.stringify(v.picks[0]);assert.equal(C.status(v.picks[0],[m],now).state,'waiting');
const later={...m,date:'2026-10-12',kickoff:'2026-10-12T18:00:00Z',status:'FINISHED',score:[1,1]};later.id=M.id(later);
assert.equal(D.key(m),D.key(later));assert.equal(C.status(v.picks[0],[later],Date.parse('2026-10-13T12:00Z')).state,'hit');assert.equal(JSON.stringify(v.picks[0]),before);
assert.equal(C.status(v.picks[0],[{...later,score:[0,1]}],Date.parse('2026-10-13T12:00Z')).state,'miss');
assert.equal(C.status(v.picks[0],[{...later,status:'POSTPONED',score:null}],now).state,'waiting');
assert.equal(C.status(v.picks[0],[{...later,status:'CANCELLED',score:null}],now).state,'void');
assert.equal(C.status(v.picks[0],[{...later,status:'AWARDED'}],Date.parse('2026-10-13T12:00Z')).state,'void');
assert.equal(C.status(v.picks[0],[{...later,conflict:{kind:'score'}}],Date.parse('2026-10-13T12:00Z')).state,'excluded');
assert.equal(C.status(v.picks[0],[{...m,date:'2026-10-10',kickoff:'2026-10-10T11:00:00Z',score:[1,0],status:'FINISHED'}],now).state,'excluded');
assert.equal(C.status(v.picks[0],[],now).state,'excluded');
assert.equal(C.status(v.picks[0],[{...later,score:null}],Date.parse('2026-10-13T12:00Z')).label,'Résultat manquant');
assert.throws(()=>C.put(v,m,'1x2',[],p,{},Date.parse(m.kickoff)),/fermé/);
assert.throws(()=>C.put(v,{...m,kickoff:null,date:'2026-10-10'},'1x2',['1'],p,{},now),/fermé/);
v=C.put(v,m,'1x2',['2'],p,{},now+1000);assert.equal(v.picks.length,1);assert.equal(v.picks[0].createdAt,new Date(now).toISOString());assert.equal(v.picks[0].savedAt,new Date(now+1000).toISOString());
v=C.put(v,m,'under:2.5',['under:2.5'],p,{},now+2000);assert.equal(v.picks.length,2);assert.equal(C.status(v.picks[1],[later],Date.parse('2026-10-13T12:00Z')).state,'hit');
const incoming=C.put({format:C.FORMAT,version:1,picks:[]},m,'1x2',['1'],p,{},now+3000),merged=C.merge(v,incoming);assert.equal(merged.kept,1);assert.deepEqual(merged.value.picks[0].choices,['2']);
const dirty=JSON.parse(JSON.stringify(v));dirty.key='DO_NOT_SAVE';dirty.picks[0].key='DO_NOT_SAVE';assert.ok(!JSON.stringify(C.validate(dirty)).includes('DO_NOT_SAVE'));
const invalid=JSON.parse(JSON.stringify(v));invalid.picks[0].savedAt=m.kickoff;assert.throws(()=>C.validate(invalid));
const double=JSON.parse(JSON.stringify(v));double.picks.push(double.picks[0]);assert.throws(()=>C.validate(double));
assert.throws(()=>C.validate({...v,picks:[{...v.picks[0],choices:['1','1']}]}));
console.log('choices: prematch locking, doubles, postponed identity, settlement, missing/conflicting results, import merge and secret stripping passed');
